arch/risc-v/src/mpfs/hardware/mpfs_timer.h
=> mpfs: MSTimer register offsets and bitmasks

drivers/mtd/m25px.c
Add support for MT25Q1G SPI NOR
=> ICICLE SPI NOR

.github/workflows/build.yml, .github/workflows/check.yml
=> Fix the check workflow for tiiuae repo

arch/risc-v/include/arch.h, arch/risc-v/include/barriers.h, arch/risc-v/src/mpfs/mpfs_allocateheap.c, arch/risc-v/src/rv64gc/riscv_mmu.h, arch/risc-v/src/rv64gc/riscv_schedulesigaction.c, arch/risc-v/src/rv64gc/riscv_swint.c, arch/risc-v/src/rv64gc/svcall.h, boards/risc-v/mpfs/icicle/scripts/Make.defs, boards/risc-v/mpfs/icicle/scripts/kernel-space.ld, boards/risc-v/mpfs/icicle/scripts/ld-envm.script, boards/risc-v/mpfs/icicle/scripts/ld-kernel.script
Preparation for enabling the kernel build for risc-v / mpfs: part2:
Some refactoring / combining of code.
Should be none as the components are not used
Untested: Testing requires that the kernel build works
=> Kernel mode prep2

arch/risc-v/src/rv64gc/riscv_assert.c
Just add the kernel stack dumping for completeness
=> Add missing code to dumpstate

arch/risc-v/src/common/riscv_pmp.c, arch/risc-v/src/mpfs/mpfs_head.S, boards/risc-v/mpfs/icicle/scripts/kernel-space.ld
Fix bugs in the MPFS protected mode build
=> Mpfs prot mode fixes

arch/risc-v/src/mpfs/mpfs_userspace.c, include/sys/syscall_lookup.h, syscall/syscall.csv
=> Two fixes from upstream

arch/risc-v/src/mpfs/hardware/mpfs_usb.h, arch/risc-v/src/mpfs/mpfs_usb.c, boards/risc-v/mpfs/common/src/mpfs_composite.c
Cherry-pick usb related fixes from upstream to our current master
Make USB work
On-desk
=> Saluki fix usb

fs/partition/fs_gpt.c
Cherry pick from upstream; fixes the GPT parsing errors
=> Fixes for GPT partition parsing

arch/risc-v/src/common/riscv_addrenv.c, arch/risc-v/src/common/riscv_mmu.h, arch/risc-v/src/mpfs/mpfs_mm_init.c
Some minor fixes from upstream NuttX
=> Fixes from upstream

arch/risc-v/src/mpfs/mpfs_fpga_canfd.c
=> arch/risc-v/src/mpfs/mpfs_fpga_canfd.c: Fix CONFIG_DEBUG_CAN_INFO ifdef

arch/arm/src/lc823450/lc823450_i2c.c, arch/arm/src/stm32f7/stm32_i2c.c, include/nuttx/clock.h
This is the change which seems to work for pixhawk testing. Same patches which are in upstream review
=> Round up sec2tick

arch/risc-v/src/mpfs/hardware/mpfs_ihc.h, arch/risc-v/src/mpfs/mpfs_ihc.c, arch/risc-v/src/mpfs/mpfs_ihc_sbi.c
=> IHC stuck fixes

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_corepwm.c
=> Mpfs config flag fixes

arch/risc-v/src/mpfs/mpfs_i2c.c
bmp388 works poorly as the system fires STOPs even in a beginning of a transaction. Don't let unrelated STOPs to distort the data flow.
=> risc-v/mpfs: i2c-fpga: fix complex transactions

arch/risc-v/src/mpfs/mpfs_usb.c, arch/risc-v/src/mpfs/mpfs_usb.h
External function to query vbus status
=> mpfs_usb: Add mpfs_vbus_detect

arch/risc-v/src/opensbi/Make.defs
Update to have 2k smaller version of OpenSBI.
RPMSG + ping + pingpongff
=> opensbi: update to contain shrinked version

arch/risc-v/src/common/riscv_pmp.c, arch/risc-v/src/mpfs/mpfs_i2c.c, libs/libc/stdio/lib_libfread.c
Two patches from upstream + 1 more thta fixes a bug in fread
=> Upstream patches

arch/risc-v/src/mpfs/mpfs_irq.c
It is possible that a PLIC IRQ is claimed but not completed at warm reset. This occurs at least if there is a fault in the middle of irq handler execution.
To recover from such situation, we can complete all IRQ:s in PLIC; this completes any already claimed IRQ, but has no effect on IRQs which are not claimed or not enabled.
=> arch/risc-v/src/mpfs/mpfs_irq.c: Fix up_irqinitialize for warm reboot

fs/hostfs/CMakeLists.txt, fs/littlefs/CMakeLists.txt, fs/partition/CMakeLists.txt, fs/procfs/CMakeLists.txt, fs/rpmsgfs/CMakeLists.txt, fs/shm/CMakeLists.txt, fs/shm/Kconfig, fs/shm/shmfs.c, fs/vfs/CMakeLists.txt, fs/vfs/fs_stat.c, include/nuttx/fs/fs.h
Also, pull pre-requisites to avoid merge conflicts
=> fs/shmfs: Fix stat() system call for shmfs object

arch/risc-v/src/mpfs/mpfs_corespi.c, arch/risc-v/src/mpfs/mpfs_i2c.c, arch/risc-v/src/mpfs/mpfs_irq.c
Backported Nuttx driver fixes for I2C, SPI and IRQ
=> 1.13.3 fc_only backported fixes (2/2)

arch/arm64/src/common/arm64_copystate.c, arch/arm64/src/common/arm64_fpu.c, arch/arm64/src/common/arm64_initialstate.c
Fix void * arithmetic to compile with -Werror
=> arch/arm64/src/common: Remove void * arithmetic

arch/arm64/src/Makefile
=> Add head to libarch

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx93/imx93_ccm.h, arch/arm64/src/imx9/hardware/imx93/imx93_pll.h, arch/arm64/src/imx9/hardware/imx9_ccm.h, arch/arm64/src/imx9/hardware/imx9_lpit.h, arch/arm64/src/imx9/hardware/imx9_lptmr.h, arch/arm64/src/imx9/imx9_ccm.c, arch/arm64/src/imx9/imx9_ccm.h, arch/arm64/src/imx9/imx9_clockconfig.c, arch/arm64/src/imx9/imx9_clockconfig.h
=> [BACKPORT] Imx9 ccm driver

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_tpm.h, arch/arm64/src/imx9/imx9_flexio_pwm.c, arch/arm64/src/imx9/imx9_tpm_pwm.c, arch/arm64/src/imx9/imx9_tpm_pwm.h
WIP: Add TPM based PWM driver for IMX9
=> arch/arm64/src/imx9: Add TPM based PWM driver for IMX9

arch/arm64/src/imx9/imx9_edma.c, arch/arm64/src/imx9/imx9_edma.h, arch/arm64/src/imx9/imx9_lowputc.h
=> Fixes for px4io

include/sys/select.h
Support defining OPEN_MAX freely to allow increasing it from 256
=> include/sys/select.h: Define __SELECT_NUINT32 in generic way

arch/arm64/src/imx9/imx9_flexspi.c, arch/arm64/src/imx9/imx9_flexspi_nor.c
Enable 4-byte addressing and adjust performance
=> Flexspi update

arch/arm64/src/imx9/imx9_flexcan.c
Add enable/disable cycle to initialize
function to speed up soft reset
=> imx9/flexcan: Add disable/enable cycle

fs/vfs/fs_poll.c
pollfd revents value is occasionally zeroed by race condition when poll_notify() is called. This results to false timeout return value from poll().
This behavior was found in uart loopback test when test application called tcdrain() before polling uart driver.
Upstream has a fix for the similar problem, but it is implemented only for serial-driver https://github.com/apache/nuttx/commit/bbb7f436d4faa33f283ac6f756b1bc9e88056dd7.
=> fs_poll: race condition protection when modifying revents value (1/2)

arch/arm64/src/imx9/imx9_lpspi.c
instead of looping just reset rxfifo
=> arch/arm64/imx9: Reset rx fifo in mode change

fs/socket/accept.c
At least on RISC-V, TCP server sockets were pretty much unusable on high load environments and kernel build.
User addresses passed to `accept()` would be accessed when the wrong MMU mappings were active. A crash would manifest when attempting to `accept()` for instance on a TCP server socket under significant load. The accept event handler would be called by the HP worker upon client connection. At this point, `accept_tcpsender()` would attempt to write to `addr` resulting in a page fault. Reproducibility would depend on the current system load (num tasks or CPU stress) but in loaded environments, it would crash almost 100% of the times.
The change should be transparent to users. `accept()` now maps pointer arguments to kernel virtual memory before proceeding. It also checks whether the …
=> Map user memory passed to accept() in kernel build

arch/risc-v/src/common/riscv_cpustart.c
=> riscv_cpustart.c: Change CPU start related traces to sinfo

.gitignore, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_ele.h, arch/arm64/src/imx9/imx9_ele.c, arch/arm64/src/imx9/imx9_ele.h, arch/arm64/src/imx9/imx9_trdc.c, tools/imx9/Config.mk, tools/imx9/Makefile.host
Move ele handling to own file from trdc
Add get key feature to ele api
Update ele FW to version 1.3.0
IMX93 bootloader
=> Implement-key-fetch-from-Edgelock-Security-Enclave

arch/risc-v/src/mpfs/hardware/mpfs_usb.h, include/nuttx/sched.h, include/nuttx/tls.h, include/sys/syscall_lookup.h, libs/libc/sched/CMakeLists.txt, libs/libc/sched/Make.defs, libs/libc/sched/task_gettid.c, libs/libc/semaphore/sem_trywait.c, libs/libc/semaphore/sem_wait.c, sched/pthread/pthread_create.c, sched/task/task_init.c, sched/tls/tls_initinfo.c, syscall/syscall.csv
A bunch of cherry-picks from upstream
=> Cherry picks from upstream

sched/mqueue/mq_rcvinternal.c, sched/mqueue/mq_sndinternal.c, sched/mqueue/msgrcv.c, sched/mqueue/msgsnd.c, sched/semaphore/sem_post.c, sched/signal/sig_dispatch.c
=> Watchdog race fixes tiiuae
