tiiuae/nuttx

arch/risc-v/src/mpfs/mpfs_clockconfig.c, arch/risc-v/src/mpfs/mpfs_spi.c, arch/risc-v/src/mpfs/mpfs_spi.h
Enable I2C0 in clockconfig and add support for board-specific SPI select logic
=> Enablers for Saluki I2C and SPI

arch/risc-v/src/mpfs/mpfs_i2c.c
=> mpfs: i2c: Using BCLK based divider

arch/risc-v/src/mpfs/mpfs_i2c.c, boards/risc-v/mpfs/icicle/include/board.h
Select the closest possible frequency which is smaller
than or equal to requested in I2C msg
=> mpfs: i2c: Add support for adaptive I2C bus frequency

arch/risc-v/src/mpfs/Make.defs, boards/risc-v/mpfs/common/kernel/mpfs_userspace.c
Userspace struct definition did not have pthread_startup
The definition for up_pthread_exit was not compiled ever
=> Fix PROTECTED_BUILD build errors for mpfs target

arch/risc-v/src/mpfs/hardware/mpfs_i2c.h, arch/risc-v/src/mpfs/mpfs_i2c.c
I2C status register reset value (0xf8) was not handled properly causing
unnecessary bus resets. Also disable interrupts while setting bus clock divider.
=>  mpfs: i2c: Fix reset and interrupt issues 

drivers/eeprom/i2c_xx24xx.c
Debug prints were not able to handle 64bit off_t and size_t.
=> drivers/eeprom/i2c_xx24xx.c: Fix compiler warnings

arch/risc-v/include/rv64gc/irq.h, arch/risc-v/include/rv64gc/syscall.h, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_allocateheap.c, arch/risc-v/src/rv64gc/riscv_swint.c, arch/risc-v/src/rv64gc/svcall.h, binfmt/binfmt_execmodule.c, sched/init/nx_start.c
Setup the correct amount of call gates and the parameters passed there
for kernel build. As far as I know, the same call gates are needed
for protected / kernel builds.
When enabling / testing the kernel build, revisit the riscv_swint
file and ensure the ABI is met. Testing the call gates is not possible
right now.
=> Prepare riscv / rv64 for CONFIG_BUILD_KERNEL

arch/risc-v/src/mpfs/Kconfig, boards/risc-v/mpfs/common/src/mpfs_boot.c, boards/risc-v/mpfs/icicle/src/mpfs_bringup.c
The image must be placed into:
boards/risc-v/mpfs/icicle/include/boot_romfsimg.h
The image is mounted by mpfs_bringup, which is run by the application
itself, or by board_late_initialize() in the case when
CONFIG_BOARD_LATE_INITIALIZE is defined, e.g. with CONFIG_BUILD_KERNEL
=> Add support for a ROMFS image for MPFS

arch/risc-v/src/mpfs/mpfs_serial.c
Number of bits was set wrongly in TCSETS for mpfs
=> arch/risc-v/src/mpfs/mpfs_serial.c: Correct setting of nbits

boards/risc-v/mpfs/icicle/src/mpfs_bringup.c
The CONFIG_ prefix was missing
=> Fix bug with ROMFS mounting in MPFS

arch/risc-v/src/Makefile, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/rv64gc/crt0.c
Contains the code for the user process signal trampoline.
This is WIP, as using the ARCH_DATA_RESERVE reference _will not work_
with risc-v. Some other solution needs to be figured out for this,
which will be done later.
=> Add crt0 file for risc-v

arch/risc-v/src/mpfs/mpfs_userspace.c
=> Fix misleading comment about usage of mstatus.mprv

arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_head.S, arch/risc-v/src/mpfs/mpfs_irq_dispatch.c, arch/risc-v/src/mpfs/mpfs_mreg.c, arch/risc-v/src/mpfs/mpfs_mreg.h, arch/risc-v/src/mpfs/mpfs_scratch.c, arch/risc-v/src/mpfs/mpfs_scratch.h, arch/risc-v/src/mpfs/mpfs_start.c
Preparation for S-mode, provide access to mhartid via the supervisor
scratch register.
=> MPFS: Context aware access to mhartid

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_emmcsd.c
This has been previously hard-coded to SD-card. Make it build time configurable.
=> arch/riscv/mpfs: Add a config flag to select SD mux state

arch/risc-v/src/mpfs/mpfs_emmcsd.c
This is a hack to make eMMC work for saluki.
The HS200 mode is currently broken;
1) the driver doesn't seem to switch to that
2) there is (most likely) bus training needed for the mode
This makes the eMMC usable until the mpfs_emmcsd is properly fixed
=> [REVERTME] Force PF eMMC always to 25MHz

arch/risc-v/src/mpfs/mpfs_opensbi.c, arch/risc-v/src/mpfs/mpfs_opensbi_utils.S, boards/risc-v/mpfs/icicle/scripts/ld-envm-opensbi.script, tools/mpfs/Config.mk
It is not really needed; g_hart_stacks is only used during SBI init as
a temporary stack area. We can use the scratch area buffers for this, as
the scratch areas define almost 4K of extra space, which is used for
exception stacks anyway.
=> mpfs: Remove the ddrstorage section from the OpenSBI package

arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_entrypoints.c, arch/risc-v/src/mpfs/mpfs_opensbi.c, arch/risc-v/src/mpfs/mpfs_start.c
Default values still come from configuration, but this gives the option
to modify the per-hart entrypoints.
=> risc-v/mpfs: Make entrypoint table run-time configurable

arch/risc-v/src/mpfs/hardware/mpfs250t_484_pinmap.h, arch/risc-v/src/mpfs/mpfs_gpio.h
- Clarify the macros MSSIO_EC_DEFAULT and MSSIO_EC_USB_DEFAULT
- Remove PULLDOWN bit from MSSIO_EC_DEFAULT, it was on by accident
- Fix some EC configuration macros; DRVSTR was wrong, clean up the others
- Define GPIO_PULLUP and GPIO_PULLDOWN like on many other platforms
=> arch/risc-v/src/mpfs: Fixes for MSSIO GPIO configurations

arch/risc-v/src/mpfs/mpfs_head.S, arch/risc-v/src/mpfs/mpfs_shead.S
a = allocated, x = executable. Otherwise the input section type will
become empty, which means output section will be empty as well.
=> mpfs_head.S: Mark .start section attributes explicitly

arch/arm/src/stm32f7/stm32_ethernet.c
Cherry-pick from upstream. Invalidation of too large area may corrupt data
=> arch/arm/stm32f7: fix cache invalidation issue in Ethernet RX

arch/risc-v/src/mpfs/mpfs_ddr.c
The DDR training IP stays active otherwise, so stop it when the training is complete.
This fixes a potential interrupt storm via MPFS_IRQ_DDRC_TRAIN.
=> mpfs/mpfs_ddr.c: Stop the DDR training once it is completed

binfmt/libelf/libelf_symbols.c
Fixes minor issue with a trace (build failure with -Werror): libelf/libelf_symbols.c:310:41: error: pointer of type 'void *' used in arithmetic [-Werror=pointer-arith]
310 |               (uintptr_t)(sym->st_value + symbol->sym_value));
=> libelf/libelf_symbols.c: Fix compilation warning about void* arithmetics

drivers/can/can.c
- buflen is long unsigned int therefore `%lu`. `%d` would trigger -Werror=format= error when building px4-firmware
- Needed for https://github.com/tiiuae/nuttx/pull/71 as requested here https://github.com/tiiuae/nuttx/pull/68#discussion_r998074669
=> caninfo print out type fix

arch/risc-v/src/mpfs/mpfs_emmcsd.c
HACK HACK HACK
This sets DDR HS + 8-bit data width mode for eMMC. This is NOT the correct way to do this.
=> mpfs/emmc: Set HS DDR + 8-bit mode

arch/arm/src/stm32f7/stm32_i2c.c
Remove unnecessary heap allocation by relocating ops inside priv data
=> arch/arm/src/stm32f7/stm32_i2c.c: Memory leak fix

arch/risc-v/src/mpfs/mpfs_fpga_canfd.c
Loopback check is not need in txpoll since it's now handled in caller devif_poll
=> Remove devif_loopback in canfd driver

arch/risc-v/src/mpfs/Kconfig
=> mpfs/Kconfig: fix typo on config file

arch/risc-v/src/mpfs/mpfs_mm_init.c, arch/risc-v/src/mpfs/mpfs_userspace.c, boards/risc-v/mpfs/icicle/scripts/ld-kernel.script
Just a temporary patch, need to implement some kind of scalable solution for this. It might be a good idea to map something else for the user to avoid using ecall to enter the kernel for simple reads ?
Also, increase the L3 table size
NOTE: Need to figure out some kind of scalable solution for this, the idea to provide a user I/O area is solid
Enables USRIO for kernel build
px4 kernel mode
=> mpfs/mpfs_mm_init: Add the MTIME user mapping for kernel mode as well

arch/risc-v/src/mpfs/mpfs_spi.c
In spi_irq handler the data is written into txfifo and transfer is started before the TXDONE interrupt is cleared. If the bus/memory access is in some cases delayed, the SPI transfer can have been finished already before the interrupt register is cleaned for the transfer.
Previous implementation leads the early arrived interrupt to be just removed and never handled, which would cause a timeout error.
This fix moves the clearing of the interrupt to the place before the TX is started, so the interrupt is not missed in above cases.
Fix is tested in dual OS system (Nuttx & Linux), where high CPU load in other OS slows down the bus/memory accesses in Nuttx side. This test setup triggers the SPI TX Timeout errors while reading peripheral registers via SPI bus. With this fix there are no SPI TX …
=> clear spi int before the transfer starts

arch/risc-v/src/mpfs/mpfs_i2c.c
In some state values the transfer is restarted in irq handler and the interrupts are disabled in the end of the function after the transfer is started. This may cause early interrupts to be accidentally cleared before they are handled leading timeout error. Interrupt clearing should be done before the transfer is restarted.
If interrupts are cleared before the transfer restart the slow bus/memory access does not affect to the timing of the start/clear operations and ints are not accidentally cleared.
Running heavy load in other operating system in dual os setup to see there is no issues in i2c transfers.
=> clear i2c ints before the transfer starts

arch/risc-v/src/mpfs/crypto.defs
Use existing pf_crypto submodule instead of cloning during build time
=> arch/risc-v/src/mpfs: symlink pf_crypto submodule

arch/risc-v/src/mpfs/mpfs_ethernet.c
There is possible deadlock situation in mpfs_network module. 
In case mpfs_receive is called, it keeps waiting for complete frame and also keeps the net_lock locked. In the mean while, the TX may run out of free descriptors, but can not get net_lock mutex lock to be able to release used descriptors. If there are no free TX descs it disables RX interrupts because it may require to send response to the received frame.
So, TX side keeps RX interrupts disabled due to lack of free descriptors and RX blocks TX to release those descs by stubbornly waiting for complete frame.
Workaround is to discard RX frame already in mpfs_interrupt_work function in case there are RX errors detected. This prevents receive method to reserve net_lock mutex in case there is no complete frame available, so TX can …
=> arch/riscv/src/mpfs/mpfs_ethernet.c: discard err rxframe in int work

arch/risc-v/src/mpfs/crypto.defs
This adds mpfs_systemservice.c into build scripts. Note that the file exists only in private repository, and this crypto.defs file is only used when CONFIG_MPFS_CRYPTO=y (which can only be enabled when the private repository is cloned)
Also remove some unneeded paths from dependency paths
=> arch/risc-v/src/mpfs/crypto.defs: Update to include mpfs_systemservice.c

arch/risc-v/src/mpfs/mpfs_emmcsd.c
Modified sendfifo() function to enable BWR_IE before checking if BWE is enabled.
In the sendfifo function there is a check if there is still remaining data to be sent and if the Buffer Write Enable status is cleared (not allowed to write more data to the buffer), the Buffer Write Ready interrupt is enabled status cleared, and function returns to wait for Buffer Write Ready. However, there is a tiny time window between the SRS09:BWE check and the SRS14:BWR int enabling where the interrupt can occur and it is then not detected causing Data Timeout error.
=> workaround for emmc interrupt blackout issue

arch/risc-v/src/mpfs/mpfs_userspace.c
The user i/o area goes over 4MB, so need more page tables
=> mpfs/mpfs_userspace: Increase user space size to 8MB

fs/cromfs/fs_cromfs.c
The logic being tested is wrong, obviously when accessing file the driver private data has to be valid (open() has been called).
=> fs/cromfs: Fix faulty DEBUGASSERT() check

net/Kconfig, net/can/can_callback.c, net/can/can_recvmsg.c
cherry-picked from upstream
https://github.com/apache/nuttx/pull/9111
net/can
saluki v2
=> net/can: fix can mssage corruption if enable NET_TIMESTAMP

arch/risc-v/src/mpfs/mpfs_fpga_canfd.c
Add missing can id transformation to IDENTIFIER_WORD
canfd driver
saluki v2
=> canfd: fix hw filter

arch/risc-v/src/mpfs/mpfs_serial.c
Don't turn off FIC3 clk which would terminate all other peripherals depending on it.
Also add a few missing undefs.
=> risc-v/mpfs: serial: fix uart closing

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_i2c.c
This adds 2 more FPGA I2Cs. Also rework the indexing so that it matches the earlier work without major changes.
=> risc-v/mpfs: i2c: add more FPGA i2cs

arch/risc-v/src/mpfs/mpfs_corespi.c
The logic for rx_fifo_empty is wrong, needs a loop for the retry to work
=> mpfs/CoreSPI: Fix bug when waiting for last character to arrive

arch/risc-v/src/mpfs/mpfs_corespi.c
Remove unnecessary reading of the status register when loading / unloading the FIFOs. Reading from the IP block is slow due to BUS synchronization and this basically makes the SPI busy loop for no reason at all, destroying the CPU usage.
The overall benefit of these changes is approx. 25%-points, which is a MASSIVE improvement.
=> mpfs/mpfs_corespi: Optimize TX / RX FIFO handling

net/can/can_callback.c, net/can/can_recvmsg.c, net/devif/devif_send.c
Fixes for iob semcount runaway problem.
net/can and net/devif
Saluki v2 UAVCAN flight
Flight now last indefinitely. Several test and no freeze so far.  iob semcount is kept in check
=> 2x can support: partial fix for iob semcount runaway 

arch/risc-v/src/mpfs/mpfs_corespi.c
Fix divider sanity check and set motorola mode 3 as default
Fix correct mode, system crash on invalid sanity check
=> mpfs/corespi: Fix minor assertion failures

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/hardware/mpfs_coremmc.h, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_coremmc.h
This adds support for the CoreMMC v3.1 FPGA driver as described in Microchip Handbook HB0510. The driver doesn't support DMA.
Initial version of the CoreMMC. Register access hangs in most boots, but with a good boot, the driver works.
So far quite minimal, such as copying / appending / creating / reading and writing files in FAT32 (64 GB card).
=> risc-v/mpfs: add CoreMMC support

arch/risc-v/src/mpfs/mpfs_dsn.c, arch/risc-v/src/mpfs/mpfs_dsn.h
- Fix retry counter handling and increase the maximum number of retries.
- Add some parenthesis for clarity.
- Change return type to signed int, as it may return -ETIMEDOUT
- Correct comment for returned value
=> arch/risc-v/src/mpfs/mpfs_dsn: Correct serial number reading routine

arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_ihc.c, arch/risc-v/src/mpfs/mpfs_ihc_sbi.c, arch/risc-v/src/mpfs/mpfs_opensbi_trap.S, arch/risc-v/src/mpfs/mpfs_opensbi_utils.S
This cleans the unnecessary flow control that's no longer needed.  Probably the support for simultaneous MP and ACK changed the environment.
Also reorganize the mpfs_opensbi_*.S so that the trap handler is easily relocated in the tlinker .ld file without the need to relocate the utils.S.  This makes it easier to follow the jump into other segment, eg. zerodevice.
RPMSG cleanup and preparations for relocating OpenSBI & friends.
Saluki v2
=> risc-v/mpfs: clean up ihc for rpmsg

arch/risc-v/src/mpfs/mpfs_ihc.c
RPMSG is associated with the use of HPWORK / LPWORK queues. After sending a message to the remote end (Linux), it waits for an ack before proceeding.
Unfortunately this may take sometimes more than 0x3000 CLINT MTIME cycles. Ack waiting is also unnecessary: nothing is done with that information. Even worse, the net_lock() is also held during the blocked time so it blocks other network stacks that are unrelated to this.
The logic is still maintained (without the ack) with the message present (MP) flag. No new message will be sent until that is cleared by the remote.
It looks like the ihc breaks the network stack by blocking within the HPWORK/LPWORK with net_lock() taken. What happens eventually:
1. Linux RPMSG tx queue gets full, no more messages may be sent
2. NuttX network stack goes out …
=> risc-v/mpfs: ihc: don't wait for a remote ack

arch/risc-v/src/mpfs/mpfs_usb.c
Currently TX_FIFO_SIZE is not altered in mpfs_ep_set_fifo_size(), but all paths (RX and TX) change MPFS_USB_RX_FIFO_SIZE only. Fix the TX_FIFO_SIZE setup.
TX_FIFO_SIZE was never configured.
Don't know
Next to none. Need some testing before upstreaming.
=> risc-v/mpfs: mpfs_usb: fix tx fifo size setup

arch/risc-v/src/mpfs/mpfs_head.S, boards/risc-v/mpfs/icicle/scripts/ld-envm-opensbi.script, boards/risc-v/mpfs/icicle/scripts/ld-envm.script
SiFive document: "ECC Error Handling Guide" states:
"Any SRAM block or cache memory containing ECC functionality needs to be initialized prior to use. ECC will correct defective bits based on memory contents, so if memory is not first initialized to a known state, then ECC will not operate as expected. It is recommended to use a DMA, if available, to write the entire SRAM or cache to zeros prior to enabling ECC reporting. If no DMA is present, use store instructions issued from the processor."
Clean the cache at this early stage so no ECC errors will be flooding later.
Cache needs to be initialized to a known state (zero)
Saluki v2 / RPMSG @ l2lim
=> risc-v/mpfs: clear L2 before use

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_ddr.c
This makes it possible to remove manual bclksclk training in case the SOC internal one is wanted to be used only.
Note that the manual addcmd training depends on having manual bclksclk training, so this dependency is managed in Kconfig
??
Tried out on saluki-pi and saluki-v2, but not properly tested on several devices.
=> arch/risc-v/src/mpfs: Clean up BCLKSCLK training

drivers/timers/pcf85263.c
Add the missing semicolons
This fixes the compilation of the RTC driver used in saluki-v3. The fix is already upstreamed.
Fixes compilation
Tested on saluki-v3, seems to work after compilation fix
=> drivers/timers/pcf85263.c: Fix compilation

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_ethernet.c, drivers/net/Kconfig, drivers/net/Make.defs, drivers/net/ksz9477.c, drivers/net/ksz9477_i2c.c, drivers/net/ksz9477_reg.h, include/nuttx/net/ksz9477.h
Adding code for saluki-v3 ethernet switch configuration.
Tested to be working on saluki-v3
=> Adding support for KSZ9477 managed ethernet switch for saluki-v3

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_dma_alloc.c, arch/risc-v/src/mpfs/mpfs_dma_alloc.h, binfmt/binfmt_execmodule.c
=> Upstream patches

arch/risc-v/src/mpfs/mpfs_ihc.c
After rebooting this ihc client hart only, ihc will hang as it's waiting for the initial handshake that just won't be there. Detect this situation and let the rptun / ihc know the master is already up. This makes the RPMSG bus usable even after NuttX reboot, in case there's not much traffic. However, Linux is likely to mark the virtio queue broken if there's descent amount of traffic. This makes the bus no longer function.
Fix NuttX <-> Linux RPMSG after NuttX reboots
NuttX <-> Linux RPMSG bus after NuttX reboot
Saluki v2
=> risc-v/mpfs: ihc: don't wait for master if it's already up

arch/risc-v/src/mpfs/mpfs_emmcsd.c
Don't allow unaligned access with the DMA requests. Return -EFAULT in case the provided address is unaligned.
DEBUGASSERTs are not necessarily enable, return an error with unaligned addresses
None
Tested 1, 2, 4 and 8 byte aligned buffers; dma rx actually works with all of the alignments
=> risc-v/mpfs: emmcsd: deny unaligned access

arch/risc-v/src/common/pgalloc.h, arch/risc-v/src/common/riscv_addrenv.c, arch/risc-v/src/common/riscv_addrenv_pgmap.c, arch/risc-v/src/common/riscv_addrenv_utils.c, arch/risc-v/src/common/riscv_mmu.h, include/nuttx/arch.h, mm/kmap/kmm_map.c, sched/misc/assert.c
Merge patches from upstream, + fix for TLS stack allocation (which is not upstreamed)
=> [BACKPORT] Pull addrenv/kmm_map related fixes from upstream

arch/risc-v/src/mpfs/mpfs_opensbi.c, arch/risc-v/src/opensbi/Make.defs
Version 1.3.1 is the latest tagged version.  This patch prepares the required changes to make v1.3.1 work.
OpenSBI 1.3.1 update
Requires also a change in:
src/mpfs_domain.c:
+mpfs_domains[i].fw_region_inited = true;
Saluki-v2 with Linux / RPMSG networking
=> risc-v/mpfs/opensbi: update opensbi to version 1.3.1

arch/risc-v/src/mpfs/mpfs_entrypoints.c, arch/risc-v/src/mpfs/mpfs_ethernet.c, arch/risc-v/src/mpfs/mpfs_head.S
Pull some commits from upstream
=> [BACKPORT] Pull PMP related changes from upstream

arch/risc-v/src/mpfs/mpfs_ddr.c
This is a collection of patches for the ddr training verify step, created during DDR initialization studies.
- More strict DQ / DQS eye sanity check; don't only check the eye width, but also centering
- Check only the TXDLY value that will actually be used
- Improve CA training verify step
This may result more errors from the ddr training verify step, but I assume that those errors are then valid ones and can be mitigated by better initialization values.
Tested on saluki-v2, testing is still ongoing
=> Ddr training improvements

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_entrypoints.c, arch/risc-v/src/mpfs/mpfs_opensbi.c
Allows board specific PMP configuration, as opposed to opening up the whole SoC for every hart.
=> mpfs_pmp: Add option to configure PMP via mpfs_board_pmp_setup

arch/risc-v/src/mpfs/hardware/mpfs_wdog.h
=> arch/risc-v/src/mpfs: Add hardware/mpfs_wdog.h

arch/risc-v/src/mpfs/mpfs_i2c.c
priv->msgid may grow past its boundaries, causing
struct i2c_msg_s *msg = &priv->msgv[priv->msgid];
to eventually cause corruption.
Fix a memory corruption issue
At least all saluki devices
Saluki v2
=> risc-v/mpfs: i2c: prevent corruption

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_tamper.c, arch/risc-v/src/mpfs/mpfs_tamper.h
This adds support for detecting various tamper events. The interrupt handler makes noise at every detection.
Perhaps easiest test is to attach JTAG debugger.
TAMPER_TESTS -define has some nonexisting (not in repos) calls, perhaps could remove it alltogether.
Simple tamper detection
Need proper FPGA
=> risc-v/mpfs: add tamper detection support

arch/risc-v/src/mpfs/mpfs_ihc.c, arch/risc-v/src/mpfs/mpfs_ihc_sbi.c
Replace DEBUGASSERTs with sanity checks. DEBUGASSERT()s are not necessarily enabled at all, thus risking the functionality especially in that case.
Don't enable the ihc irq too early. If enabled, and the master is already up, the irq is being issued so that the system gets stuck or is severely slowed down. Master may be already if this NuttX hart is rebooted, for example.
DP-7330 (partial fix)
DP-6809 (complete fix)
SalukiV2 / AMP mode with kernel / ping -A and rebooting NuttX
=> risc-v/mpfs: ihc: cleanup DEBUGASSERTs and reboot

sched/semaphore/sem_holder.c
If the semaphore is shared, the holder has put its own mmapped address to pholder->sem. This means we must switch to the holder's address environment when going through the held semaphores list.
A better option would be to get the kernel mapped address for the semaphore's physical page, but that mechanism is not functional yet.
This fixes a full system crash when CONFIG_PRIORITY_INHERITANCE=y and CONFIG_BUILD_KERNEL=y and user makes shared semaphore via:
int semfd  = shm_open("sem", O_CREAT | O_RDWR, 0666); sem_t *sem = mmap(0, sizeof(sem_t), PROT_READ | PROT_WRITE, MAP_SHARED, semfd, 0);
=> sched/sem_holder.c: When accessing SEM_WAITLIST, use holder's addrenv

arch/risc-v/src/mpfs/mpfs_corespi.c
The divider should be rounded to the next full integer to ensure that the resulting SPI frequency is <= target frequency, i.e. the SPI is not overclocked.
=> mpfs/mpfs_corespi.c: Round up divider to prevent overlock of SPI

arch/risc-v/src/mpfs/mpfs_tamper.c
Caught off means something else that was intended.
=> risc-v/mpfs: tamper: fix a typo

arch/risc-v/src/mpfs/hardware/mpfs_usb.h, arch/risc-v/src/mpfs/mpfs_usb.c
If the remote end just closes an endpoint and no longer handles it, the system is prone to intensive cpu polling via mpfs_write_tx_fifo() especially if the device side doesn't know a thing about what the remote did.
Fix this by marking the EP as dead, which will skip all writes causing unnecessary polling. The EP is back in business if the remote end sends some data (rx) or the connection is re-established.
PX4 <-> QGroundControl ACM only connection no longer spins the CPU unnecessarily
No longer high CPU loads
Saluki-v2
=> risc-v/mpfs: usb: fix fierce cpu polling if remote closes

arch/risc-v/src/mpfs/mpfs_usb.c
Currently the irq handler checks many reserved bits, which is a waste of resources:
1. pending_rx_ep bit 0 is reserved (always 0)
2. pending_rx_ep and pending_tx_ep have only bits 1, 2, 3 and 4 defined, no need to scan MPFS_USB_NENDPOINTS (9) bits as the rest are reserved
Fix this by checking only the relevant bits.
A brief performance fix
Saluki-v2 / QGroundControl app
=> risc-v/mpfs: usb: don't try nonexistent ep int flags

drivers/net/rpmsgdrv.c
Provide support for NET_RPMSG_TRANSFER only:
"It is recommended to drop all messages with commands other than NET_RPMSG_TRANSFER in function net_rpmsg_drv_ept_cb() of the flight controller."
As described in DP-7311
NuttX / AMP mode with Linux kernel / ping -A between NuttX and Linux
=> net: rpmsgdrv.c: prevent potential danger

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_tamper.c, arch/risc-v/src/mpfs/mpfs_tamper.h
mpfs_tamper driver cherry-picked from mainline
Related PR's:
-px4 fc_only: https://github.com/tiiuae/px4-firmware-fc-only/pull/46
-common: https://github.com/tiiuae/px4_boards_ssrc/pull/2
-saluki_v2: https://github.com/tiiuae/saluki-v2/pull/41
=> 1.13.3_fc_only: add mpfs_tamper driver 4/4

arch/risc-v/include/elf.h, arch/risc-v/src/common/riscv_pmp.c, binfmt/libelf/libelf_bind.c, include/nuttx/elf.h, libs/libc/machine/risc-v/arch_elf.c
Pull two changes from upstream:
1. Decreases envm usage by ~3.5K
2. Allows usage of compiler optimized memcpy et al
Note: the second commit is stripped because libs/modlib has undergone way too many changes and would necessitate pulling
in dozens of commits to get this one in.
=> Upstream fixes

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_ethernet.c
MPFS_ETHMAC_HPWORK config is missing from mpfs Kconfig
configuration can't be taken into use
=> fix MPFS_ETHMAC_HPWORK flag

arch/risc-v/src/mpfs/mpfs_corespi.c, arch/risc-v/src/mpfs/mpfs_i2c.c, arch/risc-v/src/mpfs/mpfs_serial.c
Backporting PX4 debug disable features from mainline.
Parent PRs:
https://github.com/tiiuae/px4-firmware-fc-only/pull/49
=> PX4 debug disable 5/5

arch/risc-v/src/mpfs/mpfs_emmcsd.c
Previously, address 0x03b70000u was written with shift bits that only changed the bit width, not the mode. HS mode is changed via 0x03B90100, which is required, according to Jedec specs, for DDR mode. HS mode was not applied before. Enforce DDR mode (50 MHz) for now.
The real boost, however, comes from removing the DMA limitation at 0x08xxxxxx address space, which now seems unnecessary.
This boosts the emmc write speed to approximately 3x, near 5M / sec. The greatest boost is from removing the DMA limitation, which for some reason, just works with DMA.
Only saluki-v2
=> risc-v/mpfs: emmcsd: enforce HS DDR mode

arch/risc-v/src/mpfs/mpfs_ddr.c
Set the LOCKED bit when the final ddr segmentatition is in place. Otherwise the system is prone to potential security issues if the config is altered later. Once the LOCKED bit is set, the register may no longer be changed.
As identified in DP-7916   @gpoulios , Is it possible to add Theodore Karatapanis (the reporter), I couldn't find him.
DDR config
Saluki-v2
=> risc-v/mpfs: ddr: lock segmentation registers

arch/risc-v/src/mpfs/mpfs_i2c.c
Replace risky DEBUGASSERT()s with real sanity checks. Also, do a few more checks as the system might occasionally fire an interrupt shortly after a warm reboot.
Yet, modify i2c_transfer() function so that up_disable_irq() is always called at the end to better prevent ill-timed irqs.
Prevent irqs after a warm boot
Saluki-v2 / AMP mode
=> risc-v/mpfs: i2c: perform sanity checks

drivers/net/Kconfig, drivers/net/ksz9477.c, drivers/net/ksz9477_reg.h, include/nuttx/net/ksz9477.h
Add a static port-based VLAN configuration for KSZ9477 switch. This doesn't use the VLAN tagging, but is a switch's internal mechanism to simply configure if the packet forwarding is allowed from one port to another.
=> drivers/net/ksz9477: Add simple port-based static VLAN configuration

fs/fat/fs_fat32.c, fs/fat/fs_fat32util.c
Fix the issue where fat driver is not using the last two clusters in the file system.
The fat parameter fs->fs_nclusters is the maximum number of data clusters; this doesn't include the two in the beginning. Many checks in the fat driver treat the fs->fs_nclusters-1 as being the last accessible cluster, which is not right, the last accessible one is actually this number + 2 when the cluster count includes the two first ones.
Normally this is not an issue when writes are being done through the same driver, the last two clusters are just never used. But if the filesystem is modified by external driver, for example with a populated fat created with PC, or modifying the FS via USB-MSC, this leads to the fat driver not being able to read anything that uses the last two clusters.
=> fs/fat: Fix number of data clusters usable for fat driver

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_mpu.c, arch/risc-v/src/mpfs/mpfs_mpu.h
MPUCFG registers are used to enforce memory protection for DMA master devices.
=> mpfs_mpu: Add driver to set MPUCFG registers

arch/risc-v/src/mpfs/mpfs_mpu.c, arch/risc-v/src/mpfs/mpfs_mpu.h, arch/risc-v/src/mpfs/mpfs_usb.c
=> Changes from upstream

arch/risc-v/src/mpfs/mpfs_corespi.c
After warm reset the interrupt source in the HW block is not explicitly cleared, thus once the interrupt source is enabled the old / stale interrupt fires immediately.
This causes a DEBUGASSERT() failure on line 808 mpfs_spi_unload_rx_fifo:
DEBUGASSERT(nwords > 0);
=> mpfs_corespi: Fix firing of stale interrupt after warm reset

include/cxx/cstdlib
This is the only way to get the external module "uavcanlib" to work inside the px4 kernel.
If an alternate solution, e.g. moving uavcanlib to user space is implemented this hack should be removed.
[NOT UPSTREAMABLE]
=> [HACK] cstdlib: Forward malloc et. al. to kmm_malloc, if __KERNEL__

arch/risc-v/src/mpfs/hardware/mpfs_mpucfg.h
=> mpfs_mpucfg.h: Add missing MPUCFG registers

arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_coremmc.h, arch/risc-v/src/mpfs/mpfs_emmcsd.c, arch/risc-v/src/mpfs/mpfs_sdio.c, arch/risc-v/src/mpfs/mpfs_sdio.h, arch/risc-v/src/mpfs/mpfs_sdio_dev.h, boards/risc-v/mpfs/common/src/mpfs_emmcsd.c
sdio device wrapper to support both mpfs_emmcsd and mpfs_coremmc drivers simultaneously
```
board_init ---> sdio_dev ---+----> mpfs_coremmc
|
+----> mpfs_emmcsd
```
=> wrapper to support multiple sdio device drivers

arch/risc-v/src/mpfs/mpfs_fpga_canfd.c, net/can/can_callback.c, net/can/can_recvmsg.c, net/devif/devif_send.c
This fixes the https://ssrc.atlassian.net/browse/DP-8022
The cause for the crash seems to be IOB chain corruption, which is caused by insufficient locking in the can / network stack.
The same locking issue is actually the root cause for the earlier "semcount runaway issue". Therefor, I have reverted the earlier fix for the semcount runaway issue.
The locking is added in patch "arch/risc-v/src/mpfs/mpfs_fpga_canfd.c: Fix a race condition with devif_poll"
Since the reverted patch contained also other things, I created separate patches for those. @haitomatic could you please check that those are correct; I preserved you as the "author" for those.
This PR also contains the following changes, which are not directly causing the issue, but are related:
"net/can: Release IOB when failed to queue …
=> Fix socket can race condition

arch/risc-v/src/mpfs/mpfs_fpga_canfd.c
This re-writes the ISR handling of can driver to improve real-time response and avoid lock-ups.
Also RX data buffer handling is made safe, the frame consistency is checked on every read from the RX buffer.
Fixes hangs
On-desk trials
=> Mpfs improve isr and error handling

arch/risc-v/src/common/riscv_exception.c, arch/risc-v/src/common/supervisor/riscv_perform_syscall.c, sched/group/group_killchildren.c
Fix the bugs DP-2143, DP-8522
I will still offer this to upstream review first
Increase resilience to SW bugs, don't crash the whole system if a userspace process excepts
Injected NULL dereference bugs in couple of PX4 processes, tried out that they exit without causing a panic.
=> Fix user task exit by exception

arch/arm/src/stm32f7/stm32_foc.c
This fixes build error (Werror):
Error: chip/stm32_foc.c:1918:12: error: 'stm32_foc_info_get' defined but not used [-Werror=unused-function]
1918 | static int stm32_foc_info_get(struct foc_dev_s *dev, struct foc_info_s *info)
|            ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
=> [BACKPORT] stm32f7/stm32_foc.c: Set .info_get to foc_lower_ops

arch/arm64/src/common/arm64_head.S, boards/arm64/a64/pinephone/scripts/dramboot.ld, boards/arm64/fvp-v8r/fvp-armv8r/scripts/dramboot.ld, boards/arm64/imx8/imx8qm-mek/scripts/dramboot.ld, boards/arm64/imx9/imx93-evk/scripts/dramboot.ld, boards/arm64/qemu/qemu-armv8a/scripts/dramboot.ld, boards/arm64/rk3399/nanopi_m4/scripts/dramboot.ld, boards/arm64/rk3399/pinephonepro/scripts/dramboot.ld
As __start must be placed at a precise location, a separate, explicit input section is needed to guarantee this.
Why is this an issue ? NuttX uses --entry=__start which puts __start in its correct location, but out-of-tree builds won't work, so it more robust to use an explicit section for the startup code and enforce its placement in the linker script.
=> [BACKPORT] arm64_head.S: Add explicit input section for __start

arch/risc-v/src/mpfs/mpfs_corespi.c, arch/risc-v/src/mpfs/mpfs_i2c.c, arch/risc-v/src/mpfs/mpfs_usb.c
- cherry-picked usb patch from mainline
- fixed semaphore race condition in i2c-driver
=> [1.13.3 FC_ONLY] USB and I2C fix

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_flexio.h, arch/arm64/src/imx9/imx9_flexio_pwm.c, arch/arm64/src/imx9/imx9_flexio_pwm.h
WIP: I'll send to upstream first, after the pin muxings are merged.
=> Flexio pwm

arch/risc-v/src/common/riscv_addrenv_pgmap.c
The L2 table was not connected -> results in random crashes. Also add missing data sync barrier to the end.
Fix a bug in RISC-V
MPFS
=> riscv/pgmap: Fix bug in kernel page directory init

arch/risc-v/src/mpfs/mpfs_corespi.c, arch/risc-v/src/mpfs/mpfs_i2c.c
Cherry-picked SPI and I2C semaphore race condition fixes from 1.13_fc_only
=> [mavlink 200Hz 2/2] semaphore race condition fixes from 1.13

arch/risc-v/src/mpfs/mpfs_opensbi.c, arch/risc-v/src/mpfs/mpfs_opensbi_utils.S, boards/risc-v/mpfs/icicle/scripts/ld-envm-opensbi.script, include/nuttx/tls.h
This for updating the nuttx in the saluki_bootloader_v2.
The tls warning removal is a direct cherry-pick from upstream.
Renaming the linker symbols is just a clean up; these same symbols are _ssbi_zerodev and _esbi_zerodev in the nuttx version in the bootloader currently.
Change the name to something that doesn't indicate where the sbi executable ram area is, it is anyhow determined in the linker script.
=> Remove build errors in bootloader

boards/risc-v/mpfs/common/src/mpfs_composite.c, boards/risc-v/mpfs/common/src/mpfs_emmcsd.c, boards/risc-v/mpfs/common/src/mpfs_usb.c
Add partition parsing logic to emmcsd and support for configuring either CDCACM alone or both CDCACM and USBMCS for composite mode.
This is a direct cherry-pick from upstream -> merging as is
=> boards/risc-v/mpfs/common/src: Update mpfs_emmcsd.c and mpfs_composite.c

arch/risc-v/src/common/riscv_pmp.c, arch/risc-v/src/mpfs/mpfs_mpu.c
The size must be power-of-two according to the the PMP spec.
=> riscv_pmp.c: Check that size is power of two for NAPOT

arch/risc-v/src/mpfs/mpfs_ethernet.c
Set RX buffer size to max frame length to be able to receive MC side MTU size frames
=> mpfs_ethernet.c: increase GMAC_RX_UNITSIZE

arch/risc-v/src/mpfs/mpfs_ethernet.c
gmac rx dma buffer is 64 byte aligned, so mix gmac_rx_unitsize to be aligned with that.
Relocate the UNITSIZE defines after the GMAC_MAX_FRAMELEN define to be able to use that
=> Gmac rx buf len fix

arch/risc-v/include/irq.h, arch/risc-v/include/syscall.h, arch/risc-v/src/common/riscv_exception_common.S, arch/risc-v/src/common/riscv_fork.c, arch/risc-v/src/common/riscv_internal.h, arch/risc-v/src/common/riscv_percpu.c, arch/risc-v/src/common/riscv_percpu.h, arch/risc-v/src/common/riscv_swint.c, arch/risc-v/src/common/supervisor/riscv_syscall.S
System call optimization patches from upstream
=> Syscall optimize

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_entrypoints.c
Check return value of mpfs_board_pmp_setup() and
jump to mpfs_board_pmp_error() in case of error.
=> risc-v/mpfs: Add error handling for PMP conf

drivers/net/Kconfig, drivers/net/ksz9477.c, drivers/net/ksz9477_reg.h, include/nuttx/net/ksz9477.h
Makes possible to set "a sniffer port" and forward traffic to it.
=> drivers/net/ksz9477: Add port mirroring support

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_flexspi.h, arch/arm64/src/imx9/imx9_flexspi.c, arch/arm64/src/imx9/imx9_flexspi.h, arch/arm64/src/imx9/imx9_flexspi_nor.c, arch/arm64/src/imx9/imx9_flexspi_nor.h
Pre-review for: 
https://github.com/tiiuae/nuttx/commit/be77c57ac9853169ddb7c41f7c2c343e21ddb9e0
Other patches are already merged to apache master
=> Flexspi imx9 support

.gitignore, tools/imx9/Config.mk, tools/imx9/Makefile.host
fetch fspi header and fcb generation script,
using mkimage generate nor bootable image.
=> tools/imx9: add support for norimages

arch/arm64/src/common/arm64_head.S
=> arm64: fix jump address to el2 entry when leaving el3

binfmt/libelf/libelf_load.c
Set sh_addr for regions that are not allocated. Some relocations might depend on this.
The fault in my case occurs when setting CONFIG_HAVE_CXX=y. In this case, the .ctor and .dtor sections do not get allocated, but the crt code depends on linker defined symbols _sctors/_ectors etc. These generate PC relative relocations and thus, the .ctor and .dtor output sections need an output VMA even though nothing is there. Otherwise the relocations will point to god knows where (in my case to address 0).
The problem results in full system crash later:
elf_symvalue: Other: 00000000+00000001=00000001
up_relocateadd: PCREL_HI20 at c00002dc [00000417] to sym=0x80409e80 st_value=1 _calc_imm: offset=-3221226203: hi=-786432 lo=-731
up_relocateadd: ERROR: PCREL_HI20 at c00002dc bad:ffffffff40000000 …
=> binfmt/elf_loadfile: Set sh_addr even if SHF_ALLOC == 0

arch/arm64/src/imx9/Kconfig, drivers/ioexpander/tca64xx.c
When using nuttx bootloader psci is not available in system, so chage logic so that it is behind new
configuration flag. 
Other patch fixes minor compilation errors on tca64xx ioexpander driver
=> Imx93 po patches to nuttx

drivers/ioexpander/tca64xx.c
=> drivers/ioexpander/tca64xx.c: Fix polarity register address

arch/risc-v/src/mpfs/mpfs_ethernet.c, drivers/net/ksz9477.c, drivers/net/ksz9477_reg.h
Includes a couples of fixes from the official errata.
And in separate commit custom fixes which are needed to get the camera to work.
Also removed unnecessary phyinit from mpfs_ethernet..
=> KSZ9477 errata fixes

arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/imx9_boot.c, arch/arm64/src/imx9/imx9_system_ctl.c, arch/arm64/src/imx9/imx9_system_ctl.h
Read frequency from system counter and write it
to arm register.
=> arch/arm64/imx9: Fix cntrfrq_el0 to correct value

arch/arm64/src/imx9/imx9_lpi2c.c
Clean up the interrupt-driven logic in the driver; handle error cases properly, remove dead code and simplify logic.
Fixes a load of issues with imx9 interrupt-driven i2c driver
on-desk
=> arch/arm64/src/imx9/imx9_lpi2c.c: Cleanups and error fixes

arch/arm64/src/imx9/imx9_lpi2c.c
This was left out of previous fixes, it is better to always check the remaining data counter before writing to rx buffer
=> arch/arm64/src/imx9/imx9_lpi2c.c: Ignore spurious RX interrupts

arch/risc-v/src/mpfs/mpfs_corepwm.c
Set frequency to zero and disable channels in pwm_setup() to avoid unexpected behaviour when starting PWM.
=> arch/risc-v/src/mpfs/mpfs_corepwm.c: Disable PWM channels in setup

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx93/imx93_memorymap.h, arch/arm64/src/imx9/hardware/imx9_trdc.h, arch/arm64/src/imx9/imx9_boot.c, arch/arm64/src/imx9/imx9_trdc.c, arch/arm64/src/imx9/imx9_trdc.h
Trdc is configured in EL3 bootloader
Clock pre-initialization is also executed there.
=> arch/arm64/imx9: Add trdc support

arch/arm64/src/imx9/hardware/imx9_lpi2c.h, arch/arm64/src/imx9/imx9_lpi2c.c
This adds some more robust error handling to the imx9 i2c
- Added cleanup in case of timeout
- Irq:s are enabled at once
=> Imx9 i2c fixes

drivers/net/ksz9477.c
Instead of verifying MMD indirect access by checking EEE ADVERTISEMENT register has value 0x6 (which may be changed), the verification is done by write and check LED MODE register.
1. Backup current LED_MODE register value
2. Write value Single-LED mode (0x10) to LED_MODE
3. Read LED_MODE register and verify it returns value 0x10
4. Write original (backup) value to LED_MODE
=> ksz9477: MMD indirect access check fix

arch/arm64/include/arch.h, arch/arm64/src/common/arm64_addrenv.c, arch/arm64/src/common/arm64_addrenv_perms.c, arch/arm64/src/common/arm64_addrenv_pgmap.c, arch/arm64/src/common/arm64_addrenv_utils.c, arch/arm64/src/common/arm64_internal.h, arch/arm64/src/common/arm64_mmu.c, arch/arm64/src/common/arm64_mmu.h, arch/arm64/src/common/arm64_pgalloc.c, arch/arm64/src/common/arm64_pthread_start.c, arch/arm64/src/common/arm64_task_start.c, arch/arm64/src/common/arm64_vectors.S
=> arm64/kernel mode: Pull fixes for 48-bit VA from upstream

arch/risc-v/src/mpfs/mpfs_serial.c
This is very basic functionality what we have here as we don't have RTS / CTS Flow Control in Saluki.
Disable RX interrupts and clear the FIFO in case of full RX buffer. Enable RX interrupts in case of empty buffer.
=> mpfs_serial.c: Add RX flowcontrol

arch/arm64/src/common/arm64_arch_timer.c, drivers/timers/arch_alarm.c, sched/semaphore/sem_tickwait.c
WIP: fixed arm64 tick timer
Not going to merge before upstreaming. The first patch (arch alarm) is just cleanup to make it understandable to myself. The two others actually correct something.
=> Fix arm64 tick timer

boards/arm64/imx9/imx93-evk/include/imx9_trdc_config.h
Example trdc header for bootloader build
=> boards/arm64/imx9/imx93-evk: add trdc header

arch/arm64/src/imx9/imx9_usbdev.c, drivers/usbdev/cdcacm.c, drivers/usbdev/pl2303.c
Modify cache clean/invalidate to get
mass-storage transfer work.
=> arch/arm64/imx9 Usb driver cache

drivers/usbdev/cdcacm.c
nrdq is already set 0 in resetconfig.
=> usbdev/cdcacm: Fix read queue counter in shutdown

arch/arm64/src/common/arm64_initialize.c, arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_flexcan.h, arch/arm64/src/imx9/imx9_flexcan.c, arch/arm64/src/imx9/imx9_flexcan.h, net/can/can_sendmsg.c, net/devif/devif_poll.c, net/netdev/netdev_default.c
These are clean cherry-picks from upstream to enable CAN on saluki-imx93
=> Imx9 flexcan

arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/imx9_pmic.c, arch/arm64/src/imx9/imx9_pmic.h, arch/arm64/src/imx9/imx9_reset.c
Add support to generate reset
-by ele, sending reset reques
-by pmic, making cold reset
-by watchdog, using watchdog 3
=> arc/arm64/imx9: Add reset functionality

arch/arm64/src/imx9/hardware/imx9_lpuart.h, arch/arm64/src/imx9/imx9_lowputc.c, arch/arm64/src/imx9/imx9_lpuart.c
Fix flow control for imx9 LPUART, enable RX&TX fifos, clean up interrupt handler
=> Imx9 lpuart flow control

arch/arm64/src/imx9/imx9_lpuart.c
This is a partial revert / fix for regression from 74c1dfb19
I just created a silly bug earlier. Fixing it
=> arch/arm64/src/imx9/imx9_lpuart.c: Fix parity get in TCGETS

arch/arm64/src/imx9/imx9_edma.c
Warm boot might fail if edma4 channel mux is
not written to default value
=> arch/arm64/imx9: Clear edma4 mux conf before set

drivers/ioexpander/tca64xx.c, drivers/ioexpander/tca64xx.h, include/nuttx/ioexpander/tca64xx.h
New part support added to driver,
pullup/pulldown configuration support
=> drivers/tca64xx: Add support for PCAL6416

arch/risc-v/src/common/supervisor/riscv_syscall.S
There is an enormous error in the system call dispatch logic; if a task is inside a critical section (local interrupts disabled) there is a chance that during a context switch when the task resumes, local interrupts are erroneously ENABLED. This obviously leads to unexpected crashes and such.
This happens when the CPU status has Previous Interrupt Enable (PIE) set to 1, even though Interrupt Enable (IE) is set to 0.
When the system call returns via ERET, the CPU sets PIE->IE and if PIE=1 interrupts get enabled.
This is fixed easily by explicitly CLEARING PIE from the register save area, if IE=0 when the system call was started.
Backport from upstream
=> riscv_syscall.S: Fix a massive bug in syscall dispatch logic

arch/arm64/src/imx9/imx9_lpspi.c, arch/arm64/src/imx9/imx9_lpspi.h
Hardware initialization is based refcount, not
spi enable bit. Interface to disable selected bus
added
=> arch/arm64/lspi: improve spi initialization

arch/arm64/src/imx9/imx9_lpi2c.c
imx9_lpi2c_reset didn't quite work. It tried to toggle scl line as GPIO, but the line was not even muxed properly.
Instead, set the bus to relaxed mode, and drive address 0 to the bus. This toggles the clock, and also generates start and stop sequences on the bus.
"Relaxed mode" is a new feature on the LPI2C block used in imx93.
=> arch/arm64/src/imx9/imx9_lpi2c.c: Fix bus reset

arch/arm64/src/imx9/imx9_edma.c, arch/arm64/src/imx9/imx9_flexspi_nor.c
=> Imx9 bug fixes 2511

arch/arm64/src/imx9/imx9_boot.c
MMU init must be after ddrinit.
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*
*Update this section with information on why change is necessary,
what it exactly does and how, if new feature shows up, provide
references (dependencies, similar problems and solutions), etc.*
*Update this section, where applicable, on how change affects users,
build process, hardware, documentation, security, compatibility, etc.*
*Update this section with details on how did you verify the change,
what Host was used for build (OS, CPU, compiler, ..), what Target was
used for verification (arch, board:config, ..), etc. Providing build
and runtime logs from before and after change is highly appreciated.*
=> arch/arm64/imx9: Boot, move mmu init to correct place

mm/mm_gran/mm_grantable.c
=> mm_grantable.c: Fix infinite loop due to memory fragmentation

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_head.S
L2 needs to be zeroed to make the ECC happy. However, if there's more than one bootloader in the chain, the cache doesn't need to be wiped every time. One time is enough. Thus, make this optional so that it's initialized only when really needed.
Make cache clearing optional
Bootloader
Saluki-v2
=> risc-v/mpfs: make cache clearing optional

arch/risc-v/src/mpfs/mpfs_entrypoints.c, arch/risc-v/src/mpfs/mpfs_entrypoints.h
=> mpfs_entrypoints.c: Add simple ACK mechanism for CPU boot

arch/risc-v/src/mpfs/mpfs_corespi.c
The corespi fpga block supports just one frame length, which is defined when the block is instantiated on the FPGA.
This adds support for emulating different frame lengths if they are multiples of 8-bit. That is, with 8-bit corespi one can do 8,16 and 24-bit transfers.
This is implemented by simply writing several 8-bit frames for a single word when needed.
=> arch/risc-v/src/mpfs/mpfs_corespi.c: Add support for multiple bit widths

arch/arm64/src/imx9/imx9_usdhc.c
Invalidate cache when dma transfer is ready
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*
*Update this section with information on why change is necessary,
what it exactly does and how, if new feature shows up, provide
references (dependencies, similar problems and solutions), etc.*
*Update this section, where applicable, on how change affects users,
build process, hardware, documentation, security, compatibility, etc.*
*Update this section with details on how did you verify the change,
what Host was used for build (OS, CPU, compiler, ..), what Target was
used for verification (arch, board:config, ..), etc. Providing build
and runtime logs from before and after change is highly appreciated.*
=> arch/arm64/imx9: Fix usdhc dma receive

fs/shm/shmfs_alloc.c
POSIX requires that the shm objects are zero-initialized. This has been broken in some earlier commits (starting from 9af5fc5d09724a5d300bc07ce85b9ba5c01ffadd)
Also fix the flat build memory allocation to allocate both object data and payload in the same chunk (as the comment also suggests). This saves allocations and memory in a system with lots of shm objects.
=> fs/shm/shmfs_alloc.c: Allocate zero-initialized memory in flat build

include/nuttx/addrenv.h, include/nuttx/mm/kmap.h, mm/kmap/kmm_map.c, sched/addrenv/addrenv.c, sched/semaphore/sem_holder.c, sched/semaphore/sem_waitirq.c
Semaphore fixes / patches from upstream
=> Addrenv select to kmap

sched/semaphore/sem_holder.c
=> nxsem_destroyholder: Use critical section when destroying holder(s)

arch/risc-v/src/mpfs/mpfs_ethernet.c, drivers/net/ksz9477.c, drivers/net/ksz9477_reg.h
drivers/net/ksz9477.c: Errata 16, reset SGMII always on init
net: Minor error handling improvements
=> Minor networking fixes

arch/arm64/src/common/arm64_addrenv_pgmap.c, mm/kmap/kmm_map.c
This fixes the logger issues in both imx9 and mpfs in CONFIG_BUILD_KERNEL
=> Fix kmm map

arch/risc-v/src/mpfs/mpfs_i2c.c, drivers/video/fb.c, include/nuttx/atomic.h, include/pthread.h, libs/libc/pthread/pthread_barrierdestroy.c, libs/libc/pthread/pthread_conddestroy.c, sched/pthread/pthread.h, sched/pthread/pthread_condbroadcast.c, sched/pthread/pthread_condclockwait.c, sched/pthread/pthread_condsignal.c, sched/pthread/pthread_condwait.c
pthread_cond_wait: Use atomic_t to protect the waiter count
From upstream (hopefully)
=> pthread_cond_wait: Use atomic_t to protect the waiter count

arch/arm64/src/imx9/imx9_lpuart.c, arch/risc-v/src/mpfs/mpfs_irq.c, arch/risc-v/src/mpfs/mpfs_irq_dispatch.c, arch/risc-v/src/mpfs/mpfs_plic.c, arch/risc-v/src/mpfs/mpfs_plic.h
Disable external interrupts on all harts
This solves unexpected isr assertion in SMP mode, if console is disabled later after boot
=> mpfs: Disable external interrupts on all harts

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_corespi.c
Add DMA support for SPI. SPI1, SPI2 and SPI3 may be used for the DMA currently. Also enable the DMA by default.
CoreSPI DMA support with proper FPGA
Full PX4 environment
=> risc-v/mpfs: corespi: add DMA support

arch/risc-v/src/mpfs/mpfs_ddr.c, arch/risc-v/src/mpfs/mpfs_start.c
Refining DDR training:
- Reset with WDT after completely failed training to avoid leaving "soft reset" status in the boot reason register
- Avoid unnecessary resets after failed DDR training. In most cases it is enough to reset the controller and try again. The expected failures return -EAGAIN. But also the unexpected ones typically can be re-covered by just re-training. So always re-try the ddr training after a failure, but add a re-try counter counting only the unexpected errors, just as a backup.
=> Mpfs reset with wdt after failed ddr training

arch/risc-v/src/mpfs/mpfs_ethernet.c
- Fix compilation failure "error: 'mpfs_phydump' defined but not used [-Werror=unused-function]"
- Add debug dump of phy registers.
=> arch/risc-v/src/mpfs/mpfs_ethernet.c: Fix compilation with CONFIG_DEBUG_NET

arch/risc-v/src/mpfs/hardware/mpfs_i2c.h, arch/risc-v/src/mpfs/mpfs_i2c.c, arch/risc-v/src/mpfs/mpfs_irq.c
This removes several error conditions that can be present after a failed
i2c transaction. The most important of them is the priv->sem_isr semaphore
which can be signaled due to a race condition.
This also ensures the i2c device itself is in idle state before futzing
around with it.
MPFS target, i2c driver only
MPFS
=> mpfs_i2c: Clean up the logic in i2c_transfer

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_coremmc.c
For Flat build poll lines_busy loop only short time at once and sleep for one system tick between checks if still busy.
Bus width and Fiq0 clock fixed.
This workaround is needed because coremmc does not have Transfer Completed interrupt, but the BUSY state shall be read from status register by polling. Just running in busy loop would cause very high cpuload by thread using the write operation of coremmc.
=> Coremmc performance workaround

libs/libc/modlib/modlib_bind.c
Addrenv is changed to the newly created process' one in the beginning of modlib_bind, and needs to be changed always when returning from the function; also in error cases.
=> libs/libc/modlib/modlib_bind.c: Fix system crash if modlib_bind fails

arch/risc-v/src/mpfs/mpfs_corespi.c
16-bit DMA transfer was of incomplete size. Also the endian was wrong.
=> risc-v/mpfs: corespi: fix 16-bit dma transfer

arch/risc-v/src/mpfs/mpfs_irq.c
From Polarfire SoC TRM:
6.5.8 Interrupt Completion
To signal the completion of executing an interrupt handler, the processor core writes the received interrupt ID to the Claim/Complete register. The PLIC does not check whether the completion ID is the same as the last claim ID for that target. If the completion ID does not match an interrupt source that is currently enabled for the target, the completion is ignored.
The last paragraph clearly states that IRQ completion does not work for sources that have been disabled -> must ACK the completion before disable.
This fixes interrupt handling on MPFS.
MPFS
=> mpfs_irq.c: Interrupt claim must be cleared before disabling the source

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_sdio_dev.h, drivers/mmcsd/mmcsd_sdio.c
If CONFIG_MMCSD_SDIOWAIT_WRCOMPLETE is defined, the coremmc driver uses SD card's dat0 line to detect whether the sd card is still busy.
This requires that the FPGA design using coremmc block wires dat0 line to some fabric irq; and configures CONFIG_MPFS_COREMMC_WRCOMPLETE_IRQNUM to point to that. Default for the irq number is 4. (MSS_INT_F2M_4)
=> arch/risc-v/src/mpfs: Implement wrcomplete support for coremmc driver

arch/arm64/src/imx9/hardware/imx9_ele.h, arch/arm64/src/imx9/imx9_ele.c, arch/arm64/src/imx9/imx9_ele.h
Add ELE events API function
Add device lifecycle API function
Add close device API function
NXP93
=> Add-NXP93-ELE-events-fetch

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/mpfs_ethernet.c
This timeout timer makes very lengthy operations such as re-initializing PHY.
=> mpfs/ethernet: Move txtimeout from HPWORK to LPWORK

sched/semaphore/sem_recover.c, sched/semaphore/sem_wait.c, sched/semaphore/sem_waitirq.c
The kernel mapping should be performed in sem_wait (thread level) as virtual memory mappings cannot be added from interrupt, at least for now.
The reason?
kmm_map() depends on mm_map_add(), which in turn uses a mutex for mutual exclusion. Using mutexes from interrupt level is not permitted.
Mapping tcb->waitobj into kernel virtual memory directly in sem_wait() makes sense, since accessing tcb->waitobj via a user virtual address can lead to unexpected results (the wrong mappings can be in place).
=> sched/sem_waitirq: Move kmm_map() call to sem_wait()

arch/risc-v/src/mpfs/mpfs_corespi.c
This is done in FPGA, but needs the same addressing in here as well.
=> risc-v/mpfs: corespi: separate tx and rx buffers

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/hardware/mpfs_fpga_sysreg.h, arch/risc-v/src/mpfs/hardware/mpfs_sysreg.h, arch/risc-v/src/mpfs/mpfs_corepwm.c, arch/risc-v/src/mpfs/mpfs_corespi.c, arch/risc-v/src/mpfs/mpfs_fpga_canfd.c, arch/risc-v/src/mpfs/mpfs_i2c.c, arch/risc-v/src/mpfs/mpfs_lowputc.c, arch/risc-v/src/mpfs/mpfs_rcc.c, arch/risc-v/src/mpfs/mpfs_rcc.h, arch/risc-v/src/mpfs/mpfs_serial.c
Needs FPGA + bootloader update
=> fpga: Add reset controller for FPGA peripherals

arch/risc-v/src/mpfs/mpfs_entrypoints.c
Otherwise we get an undefined symbol error when LIBC_ARCH_ATOMIC is defined.
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*
*Update this section with information on why change is necessary,
what it exactly does and how, if new feature shows up, provide
references (dependencies, similar problems and solutions), etc.*
*Update this section, where applicable, on how change affects users,
build process, hardware, documentation, security, compatibility, etc.*
*Update this section with details on how did you verify the change,
what Host was used for build (OS, CPU, compiler, ..), what Target was
used for verification (arch, board:config, ..), etc. Providing build
and runtime logs from before and after change is highly …
=> mpfs/mpfs_entrypoints.c: Change atomic_load > atomic_read

arch/risc-v/src/mpfs/hardware/mpfs_usb.h, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_dsn.c, arch/risc-v/src/mpfs/mpfs_emmcsd.c, arch/risc-v/src/mpfs/mpfs_ethernet.c, arch/risc-v/src/mpfs/mpfs_sdio_dev.h, arch/risc-v/src/mpfs/mpfs_usb.c
This replaces the big kernel lock (enter/leave_critical_section()) with local spinlocks from all MPFS drivers that still use it. The reason is obviously to alleviate big kernel lock congestion which has a massive performance impact in SMP:
Only the MPFS target is impacted.
App impact: No
Doc impact: No
Build system impact: No
Tested with private downstream MPFS target that uses all of the changed drivers.
=> arch/risc-v/mpfs: Remove big kernel lock from several drivers

arch/risc-v/src/mpfs/mpfs_corepwm.c
Releasing the I2C reset does nothing for PWM; try releasing PWM reset instead.
MPFS PWM functionality only. Nothing else is impacted.
Downstream MPFS target with PWM output
=> mpfs_corepwmc.c: Fix release of reset

arch/risc-v/src/mpfs/hardware/mpfs_usb.h, arch/risc-v/src/mpfs/mpfs_coremmc.c, arch/risc-v/src/mpfs/mpfs_emmcsd.c, arch/risc-v/src/mpfs/mpfs_usb.c
In SMP mode one CPU can be executing the MMC interrupt while another CPU
disables (e.g. via watchdog timeout). As it is disabled the other CPU
assumes it's safe to start configuring the device after this.
This causes a leak in the driver's private data as well as a mutual
exclusion leak on the device itself.
Fix this by aborting any triggered interrupt by checking whether it's
even enabled.
=> mpfs_emmcsd/coremmc.c: Check if received state interrupt in SMP mode

sched/sched/sched_backtrace.c, sched/sched/sched_setpriority.c, sched/sched/sched_suspend.c, sched/signal/sig_dispatch.c, sched/task/task_restart.c, sched/task/task_terminate.c
=> sched/affinity: Fix CPU_LOCKED functionality for some SMP calls

sched/semaphore/sem_holder.c, sched/semaphore/sem_post.c, sched/semaphore/sem_waitirq.c
This PR fixes random semaphore related crashes:
- There was a bug in sem_post, setting the blocking bit wrongly
- There is a bug in removing mutex holder structures, causing randomly holder not being removed, and leaving a deleted tasks tcb in semaphore, which was then accessed in priority restoration
- There was some unnecessary code in waitirq
=> Sched semaphore fix sem recover

Kconfig
It is not dependent on NDEBUG at all. Userspace assert() is, but with this dependency the kernel PANIC()s don't show file/line either.
*Note: Please adhere to [Contributing Guidelines](https://github.com/apache/nuttx/blob/master/CONTRIBUTING.md).*
*Update this section with information on why change is necessary,
what it exactly does and how, if new feature shows up, provide
references (dependencies, similar problems and solutions), etc.*
*Update this section, where applicable, on how change affects users,
build process, hardware, documentation, security, compatibility, etc.*
*Update this section with details on how did you verify the change,
what Host was used for build (OS, CPU, compiler, ..), what Target was
used for verification (arch, board:config, ..), etc. Providing build
and …
=> [NOT UPSTREAM] assert: Remove dependency to !NDEBUG for ASSERT_FILENAME

arch/arm/src/armv7-a/arm_perf.c, arch/arm/src/armv7-m/arm_perf.c, arch/arm/src/armv7-r/arm_perf.c, arch/arm/src/armv8-m/arm_perf.c, arch/arm/src/armv8-r/arm_perf.c, arch/arm64/src/common/arm64_perf.c, arch/risc-v/Kconfig, arch/risc-v/src/common/riscv_perf_cycle.c, arch/risc-v/src/common/riscv_perf_time.c, arch/risc-v/src/esp32c3-legacy/esp32c3_perf.c, arch/risc-v/src/mpfs/Make.defs, arch/risc-v/src/mpfs/mpfs_perf.c, arch/x86_64/src/intel64/intel64_perf.c, arch/xtensa/src/common/xtensa_perf.c, drivers/timers/arch_alarm.c, drivers/timers/arch_timer.c
Add up_perf_ functions for MPFS, which don't rely on alarm/oneshot interface.
Also add optimized up_udelay and up_ndelay functions, which use the MTIMER directly to measure time; making them accurate and more multithreading frendly.
=> arch/risc-v/mpfs: Add optimized perf timer functions for mpfs

Documentation/guides/index.rst, Documentation/guides/optee.rst, arch/arm64/include/imx9/imx9_ahab.h, arch/arm64/include/imx9/imx9_romapi.h, arch/arm64/include/syscall.h, arch/arm64/src/Toolchain.defs, arch/arm64/src/cmake/Toolchain.cmake, arch/arm64/src/imx9/Kconfig, arch/arm64/src/imx9/Make.defs, arch/arm64/src/imx9/hardware/imx9_ele.h, arch/arm64/src/imx9/imx9_ahab.c, arch/arm64/src/imx9/imx9_boot.c, arch/arm64/src/imx9/imx9_ele.c, arch/arm64/src/imx9/imx9_ele.h, arch/arm64/src/imx9/imx9_romapi.c, drivers/misc/CMakeLists.txt, drivers/misc/Kconfig, drivers/misc/Make.defs, drivers/misc/optee.c, drivers/misc/optee.h, drivers/misc/optee_smc.c, drivers/misc/optee_smc.h, drivers/misc/optee_socket.c, include/imx_container.h, include/nuttx/tee.h, tools/nxstyle.c
This PR includes cherry-picked commits from the upstream, apache nuttx repo, that haven't been merged yet.
The main functionality these commits bring is:
-  ELE functionality to support AHAB boot and TRNG (True Random Number Generator).
- Introduce the imx9 ROMAPI which is currently required by the AHAB boot, and decouples the boot media from the bootloader firmware.
- imx9 AHAB boot API.
- Option to disable MMU (this was necessary for the stripped down version of the bl2 bootloader).
- Ability to build an imx9 bootloader either in EL3(bl2) or EL1(bl33) (before this PR, only EL3 builds were allowed).
- OP-TEE smc driver, to enable communication between the non-secure and the secure world.
- OP-TEE driver for shared memory allocation and registration.
=> Imx9 secure world

arch/arm64/src/imx9/imx9_lpuart.c
This reverts commit 83a119160c03f5910bd76ab07c9e19cbfa1e82d4.
This commit broke the GPS; the issue needs more investigation
=> Revert "imx9/lpuart: Fix SMP deadlock with imx9_txint"

arch/arm64/src/imx9/imx9_lpuart.c
I had to revert one of SMP related lpuart commits earlier, because it broke the uart in single CPU
This reverts that revert, and adds a fix for the original issue. After this, the SMP boots ok on imx9
=> Imx9 fix lpuart for smp

arch/arm64/src/imx9/imx9_boot.c
Move uart low level init to bl2 only. No need to reinit uart on bl33 again.
Swap uart init and board init (uart is used on board init) 
IMX93
Saluki nxp93
=> arch/arm64/imx9: Fix uart init for bl2

arch/arm64/src/imx9/imx9_boot.c
Move uart low init from bl2 only to original place
Imx9 boot and uart
Custom imx9 hardware
IMX9 PX4 uarts are again working
=> Imx9 fix lpuart init

arch/risc-v/src/mpfs/Kconfig, arch/risc-v/src/mpfs/hardware/mpfs_i2c_ext.h, arch/risc-v/src/mpfs/mpfs_i2c.c
This adds the I2C extension support to the CoreI2C, enabling smart FIFO reads & writes
=> arch/mpfs: Add I2C extension IP support

arch/arm64/src/imx9/imx9_usbdev.c
The interrupt handler accesses the device as well as the driver's private data. Use critical_section for mutual exclusion with drivers/usbdev, which also protects the same data with critical_section.
=> imx9/imx9_usbdev.c: Fix interrupt handling in SMP mode
